name: Release

# This workflow runs platform-specific release workflows, collects platform-specific artifacts
# and creates a GitHub Release with all the artifacts attached.

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+' # run on push to tags matching X.Y.Z

jobs:
  # Run the Apple release workflow
  release_apple:
    uses: ./.github/workflows/release_apple.yml
    with:
      tag: ${{ github.ref_name }}

  # Add other platform-specific release jobs here as they are added.
  release_windows:
    uses: ./.github/workflows/release_windows.yml
    with:
      tag: ${{ github.ref_name }}
    secrets: inherit

  # Run the Apple release workflow
  release_android:
    uses: ./.github/workflows/release_android.yml
    with:
      tag: ${{ github.ref_name }}

  release:

    runs-on: ubuntu-latest
    # Wait for the Android, Apple and Windows release workflows to complete
    # Add more platform-specific jobs here as they are added.
    needs: [release_apple, release_windows, release_android]

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true

      - name: Create release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create ${{ github.ref_name }} --generate-notes artifacts/*
